[package]
name = "kspy"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
k8s-openapi = { version = "0.22.0", features = ["latest"] }
kube = "0.93.1"
tokio = { version = "1.40.0", features = ["macros", "rt", "rt-multi-thread"] }
